---
created_at: 2016-05-04T16:46:40+0900
title: "これが……これが俺たちの新しいブログだ！"
htags:
  - "ロ技研/おしらせ"
kind: article
authors:
  - "2014/larry/syskan"

excerpt: "新しいブログのお披露目です。"
---

ブログとwikiを一新した話をします。

== TL;DR
- link:https://blog.rogiken.org/[ブログ] と link:https://wiki.rogiken.org/[wiki] を新しく作ったので使ってください。
- 良い機会なのでgitに慣れましょう。
- 山奥の秘境での作業者にも優しい設計です。
- vim使おうな！

== 獲得と喪失
まず昨年のシス管の内部事情を3行で。

....
「今のサーバOBさんに借りてるやつだからロ技研が自前で借りるべきじゃね？」
「webは移行できたけどwikiがPHPバージョンとかいろいろ古すぎてつらい、これ保守するの厳しい」
「そんなこんなのうちに旧サーバにアクセスできなくなってた……」
....

うーん。 +
とまあこういう経緯で、我々はサーバを手に入れ、そしてwikiを失ったのです。

== 征服感
さて件のwikiというのはPHPで動くものでしたが、長らくアップデートされていなかったようで、もはや面倒な手順を踏まねばアップデートしてサーバを移行できないほど古いものでした。 +
サーバ側に置いてあるファイルを見ても独自のwiki記法だし、wikiの内容を見るのにPHPの動くサーバを用意しなければいけないのも面倒です。

- PHPの動くwebサーバを用意しなければwikiを閲覧・編集できない
- 独自wiki記法のせいで他への移行が面倒(移行先が制限されてしまう)

このような欠点を解消する方法を、私は知っていました。 +
**静的サイトジェネレータ**と呼ばれるものです。

静的サイトジェネレータとは、ファイル群を変換してwebサイト(のhtml等)を生成するソフトウェアの一般名称です。 +
その根底には、「webアプリ等でもないのに、単なるwebサイトを見るために裏でPHPなどの高度なプログラムを動かすのは、やりすぎである」という思想があります。 +
wikiやブログも、単に閲覧する際にはデータがダイナミックに変化するものでもないし、純粋なwebサーバ以外の機能が必要になるのは**記事の投稿・編集等のタイミングだけ**です。 +
なら、そのファイル変換とかの部分は外部のソフトウェアに任せた方が良いでしょう。 +
**ひとつのことをうまくやるプログラムを協調させる**、いわゆるUNIX哲学みたいな発想です。 +
**疎結合**にすることで、気に要らない部分だけを挿げ替えることが簡単にできるようになります。

この方針により、wiki(またはブログ)は大まかに次の部分に分割されることとなります。

- webサーバ
- ソースファイルを変換してwiki/ブログのwebサイトを生成する
- ソースファイルを特定の人々が編集できるようにする

これらのすべてを自前で用意するか、或いは簡単に別サービスに切り替え可能にすることで、「特定のサービスがなければ運用できない/運用が困難になる」という現象(いわゆる**link:https://ja.wikipedia.org/wiki/%E3%83%AD%E3%83%83%E3%82%AF%E3%82%A4%E3%83%B3%E5%8A%B9%E6%9E%9C[ロックイン]**)を防ぎ、システム全体を掌握することができるようになります。 +
後の世代がメンテナンスしたり、別のサービスやソフトウェアに乗り換えたりするとき楽になるはずです。

=== webサーバ
webサーバは、自前で動かしている link:https://www.rogiken.org/[ロ技研のwebページ] と同じものを使えます。 +
副作用として、 rogiken.org のドメインを使えるようになります。

=== ソースファイルを変換するやつ
これがまさに静的サイトジェネレータの役割です。 +
諸事情(というか個人的な事情)があり、私個人のブログで使っていた link:http://nanoc.ws[nanoc] というものを利用することにしました。 +
自作プラグインによる拡張も、生のRubyで書けるので容易です。
(まあ、やりすぎると他への移行が面倒になりますが。)

また、nanocに限らず多くの静的サイトジェネレータは、プレビュー用に自前のサーバ機能を持っており、ソースファイルが手元にあればその完成形を見ることができます。 +
つまり、**山奥のネットの繋がらない秘境に篭っても、手元にソースとRuby環境さえあればwikiやブログを閲覧・編集できる**ということです。

=== ソースファイルを特定の人々が編集できるようにするやつ
多人数で開発し、競合をうまく解決し、テキストのバージョン管理に向いている。 +
まさしくVCS(バージョン管理システム)です。

今回は、今をときめく**git**と、そのプラットフォームである**GitHub**を使うことにしました。 +
wikiは link:https://github.com/titech-ssr/wiki.rogiken.org[こちら] 、ブログは link:https://github.com/titech-ssr/blog.rogiken.org[こちら] です。 +
プログラマに限らず、何かの開発をする人はgit等を使えるに越したことはないので、部員の皆さんに慣れてもらう良い機会です。

また、これはgitではなくGitHubやGitLab等の機能ですが、Issueなどを使うことにより記事の内容に関するツッコミや質問なども管理できます。 +
コメント機能に近いものです。 +
攻撃的な鉞も、Issuesに投げればきっと誠心誠意対応してもらえることでしょう。

=== 連携
今回、 link:https://jenkins.io/[Jenkins] というCI(継続的インテグレーション)ツールを使って、上で挙げた3要素の連携を行いました。 +
部員の皆さんがGitHubへ更新をpushすれば、自動でファイル変換が実行され、webサーバのデータが更新されます。 +
というわけで、これなら既存のwikiやブログと大して手間は変わらないだろうと思います。

=== その他
皆さんが自分のお好きなエディタで記事を書けるようになります。 +
link:https://asciidoclive.com/[AsciiDocLIVE] 等のサービスでWYSIWYGしても良いし、vimやEmacsで書いても良いでしょう。

執筆者だけでなく、利用者にも優しい仕組みになっています。 +
「使われている画像を全てダウンロードしたい」なんて場合も、いちいちスクリプトを書いてクロールしたりせずとも、リポジトリから画像ファイルを抽出するだけです。 +
検索だって、ダウンロードしてしまえばただのテキストですから、grep等好きなツールで検索することもできます。

== ファイル形式
ファイル形式にはmarkdownでなく**AsciiDoc**を採用しました。 +
markdownのように方言が沢山あるわけではなく、安心して残せる形式だからです。 +
他にも、htmlの埋め込みが明示的に行えるとか、そもそもhtmlを使わずともmarkdownより遥かに表現力が高いとか、docbookの面影を残した設計になっていて技術文書に向いているとか、いろいろ理由はあります。

ともかく、これで**マウスポチポチかhtml直書きという究極の2択を回避**して記事を書けます。 +
[small]#(まあ私はHTML直書き大好きですが……)#

== スタイル
ページのHTMLテンプレートも自前で用意したものなので、弄り放題です。 +
ダサいスタイルは変更しましょう。 +
というかこのブログも今はショボい見た目ですが、そのうち何とかします。
したいです。
できればいいなぁ。

== まとめ
- link:https://blog.rogiken.org/[ブログ] と link:https://wiki.rogiken.org/[wiki] を新しく作ったので使ってください。
- 良い機会なのでgitに慣れましょう。
- 山奥の秘境での作業者にも優しい設計です。
- vim使おうな！
